#include<iostream>

using namespace std;

int board[4][4];
int line[] = {1,0,-1,0};
int column[] = {0,1,0,-1};

void newgame(){
    for(int i=0; i<4; i++){
        for(int j=0; j<4; j++){
            board[i][j] = 1;
        }
    }
}

void printui(){
    for(int i=0; i<4; i++){
        for(int j=0; j<4; j++){
            if(board[i][j] = 0)
                cout << " ";
            else
                cout << board[i][j] << endl;
        }
    }
    cout << "n : new game , q : quit , w : up , s : down , a : right , d : left";
}

int main(){
    char commandtodir[128];
    commandtodir['W'] = 0;
    commandtodir['S'] = 1;
    commandtodir['A'] = 2;
    commandtodir['D'] = 3;
    while(true){
        printui();
        char command;
        cin >> command;
        if(command == 'n')
            newgame();
        else if(command == 'q')
            break;
        else{
            int currentdirection = commandtodir[command];
            cout << currentdirection << endl;
        }
    }
    return 0;
}

   


